services:

  db:
    image: mariadb:11.6
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: xHeslo123
    volumes:
      - database:/var/lib/mysql:Z
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  database:
